[[[cog

import sys
sys.path.append('/home/ksakash/archives/robocomp/python')

import stringcase as sc
import cog
def A():
	cog.out('<@@<')
def Z():
	cog.out('>@@>')
def TAB():
	cog.out('<TABHERE>')
def SPACE(i=0):
	s = ''
	if i>0:
		s = str(i)
	cog.out('<S'+s+'>')


#from dsl_parsers.parsing_utils import gimmeIDSLStruct
from dsl_parsers.dsl_factory import DSLFactory
customTypesList = []

includeDirectories = theIDSLPaths.split('#')
#idsl = gimmeIDSLStruct(theIDSL, files='', includeDirectories=includeDirectories)
idsl = DSLFactory().from_file(theIDSL)
for imp in idsl['types']:
	if imp['type'] in ('sequence', 'struct'):
		customTypesList.append(imp)
	if imp['type'] == 'struct' and imp['name'] == structName:
		for structVar in imp['structIdentifiers']:
			wascustomType = False
			for customType in customTypesList:
				if structVar['identifier'] == customType['name']:
					if customType['type'] == 'sequence':
						if customType['typeSequence'] in ('float','int'):
							cog.outl(customType['typeSequence'].split('/')[-1] +"32[] " + sc.snakecase(structVar[1]))
						else:
							cog.outl(sc.pascalcase(customType['typeSequence'].split('/')[-1]) +"[] " + sc.snakecase(structVar[1]))
						wascustomType = True
						break
					elif structVar[0] == 'struct':
						cog.outl(sc.pascalcase(customType['name'].split('/')[-1]) +" " + sc.snakecase(structVar[1]))
						wascustomType = True
						break
			if not wascustomType:
				if structVar['type'] in ('float','int'):
					cog.outl(structVar['type']+"32 "+sc.snakecase(structVar['identifier']))
				else:
					str = structVar['type'].split('::')[-1]+" "+sc.snakecase(structVar['identifier'])
					cog.outl(str.replace("::", "ROS/"))
	elif imp['type'] == 'sequence' and imp['name'] == structName:
		msg = ''
		if imp['typeSequence'] in ('float','int'):
			msg = imp['typeSequence'].split('::')[-1] +"32[] " + sc.snakecase(structName)
		else:
			msg = sc.pascalcase(imp['typeSequence'].split('::')[-1]) +"[] "+ sc.snakecase(structName)
		# print ("msg", msg)
		cog.outl(msg.replace("::", "ROS/"))
]]]
[[[end]]]
