// Generated by gencpp from file RoboCompLaserROS/getLaserAndBStateData.msg
// DO NOT EDIT!


#ifndef ROBOCOMPLASERROS_MESSAGE_GETLASERANDBSTATEDATA_H
#define ROBOCOMPLASERROS_MESSAGE_GETLASERANDBSTATEDATA_H

#include <ros/service_traits.h>


#include <RoboCompLaserROS/getLaserAndBStateDataRequest.h>
#include <RoboCompLaserROS/getLaserAndBStateDataResponse.h>


namespace RoboCompLaserROS
{

struct getLaserAndBStateData
{

typedef getLaserAndBStateDataRequest Request;
typedef getLaserAndBStateDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getLaserAndBStateData
} // namespace RoboCompLaserROS


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::RoboCompLaserROS::getLaserAndBStateData > {
  static const char* value()
  {
    return "439e5adff77032847b0c33145cb20fb2";
  }

  static const char* value(const ::RoboCompLaserROS::getLaserAndBStateData&) { return value(); }
};

template<>
struct DataType< ::RoboCompLaserROS::getLaserAndBStateData > {
  static const char* value()
  {
    return "RoboCompLaserROS/getLaserAndBStateData";
  }

  static const char* value(const ::RoboCompLaserROS::getLaserAndBStateData&) { return value(); }
};


// service_traits::MD5Sum< ::RoboCompLaserROS::getLaserAndBStateDataRequest> should match
// service_traits::MD5Sum< ::RoboCompLaserROS::getLaserAndBStateData >
template<>
struct MD5Sum< ::RoboCompLaserROS::getLaserAndBStateDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::RoboCompLaserROS::getLaserAndBStateData >::value();
  }
  static const char* value(const ::RoboCompLaserROS::getLaserAndBStateDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::RoboCompLaserROS::getLaserAndBStateDataRequest> should match
// service_traits::DataType< ::RoboCompLaserROS::getLaserAndBStateData >
template<>
struct DataType< ::RoboCompLaserROS::getLaserAndBStateDataRequest>
{
  static const char* value()
  {
    return DataType< ::RoboCompLaserROS::getLaserAndBStateData >::value();
  }
  static const char* value(const ::RoboCompLaserROS::getLaserAndBStateDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::RoboCompLaserROS::getLaserAndBStateDataResponse> should match
// service_traits::MD5Sum< ::RoboCompLaserROS::getLaserAndBStateData >
template<>
struct MD5Sum< ::RoboCompLaserROS::getLaserAndBStateDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::RoboCompLaserROS::getLaserAndBStateData >::value();
  }
  static const char* value(const ::RoboCompLaserROS::getLaserAndBStateDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::RoboCompLaserROS::getLaserAndBStateDataResponse> should match
// service_traits::DataType< ::RoboCompLaserROS::getLaserAndBStateData >
template<>
struct DataType< ::RoboCompLaserROS::getLaserAndBStateDataResponse>
{
  static const char* value()
  {
    return DataType< ::RoboCompLaserROS::getLaserAndBStateData >::value();
  }
  static const char* value(const ::RoboCompLaserROS::getLaserAndBStateDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOCOMPLASERROS_MESSAGE_GETLASERANDBSTATEDATA_H
