// Generated by gencpp from file RoboCompLaserROS/getLaserConfDataResponse.msg
// DO NOT EDIT!


#ifndef ROBOCOMPLASERROS_MESSAGE_GETLASERCONFDATARESPONSE_H
#define ROBOCOMPLASERROS_MESSAGE_GETLASERCONFDATARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <RoboCompLaserROS/LaserConfData.h>

namespace RoboCompLaserROS
{
template <class ContainerAllocator>
struct getLaserConfDataResponse_
{
  typedef getLaserConfDataResponse_<ContainerAllocator> Type;

  getLaserConfDataResponse_()
    : response()  {
    }
  getLaserConfDataResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef  ::RoboCompLaserROS::LaserConfData_<ContainerAllocator>  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct getLaserConfDataResponse_

typedef ::RoboCompLaserROS::getLaserConfDataResponse_<std::allocator<void> > getLaserConfDataResponse;

typedef boost::shared_ptr< ::RoboCompLaserROS::getLaserConfDataResponse > getLaserConfDataResponsePtr;
typedef boost::shared_ptr< ::RoboCompLaserROS::getLaserConfDataResponse const> getLaserConfDataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator1> & lhs, const ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator1> & lhs, const ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace RoboCompLaserROS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3961fdd4f8941291375026213e8b0e82";
  }

  static const char* value(const ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3961fdd4f8941291ULL;
  static const uint64_t static_value2 = 0x375026213e8b0e82ULL;
};

template<class ContainerAllocator>
struct DataType< ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RoboCompLaserROS/getLaserConfDataResponse";
  }

  static const char* value(const ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "LaserConfData response\n"
"\n"
"\n"
"================================================================================\n"
"MSG: RoboCompLaserROS/LaserConfData\n"
"string driver\n"
"string device\n"
"int32 staticConf\n"
"int32 maxMeasures\n"
"int32 maxDegrees\n"
"int32 maxRange\n"
"int32 minRange\n"
"int32 iniRange\n"
"int32 endRange\n"
"int32 cluster\n"
"int32 sampleRate\n"
"float32 angleRes\n"
"float32 angleIni\n"
;
  }

  static const char* value(const ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getLaserConfDataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RoboCompLaserROS::getLaserConfDataResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    s << std::endl;
    Printer< ::RoboCompLaserROS::LaserConfData_<ContainerAllocator> >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCOMPLASERROS_MESSAGE_GETLASERCONFDATARESPONSE_H
