// Generated by gencpp from file RoboCompLaserROS/getLaserDataResponse.msg
// DO NOT EDIT!


#ifndef ROBOCOMPLASERROS_MESSAGE_GETLASERDATARESPONSE_H
#define ROBOCOMPLASERROS_MESSAGE_GETLASERDATARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <RoboCompLaserROS/TLaserData.h>

namespace RoboCompLaserROS
{
template <class ContainerAllocator>
struct getLaserDataResponse_
{
  typedef getLaserDataResponse_<ContainerAllocator> Type;

  getLaserDataResponse_()
    : response()  {
    }
  getLaserDataResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef  ::RoboCompLaserROS::TLaserData_<ContainerAllocator>  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct getLaserDataResponse_

typedef ::RoboCompLaserROS::getLaserDataResponse_<std::allocator<void> > getLaserDataResponse;

typedef boost::shared_ptr< ::RoboCompLaserROS::getLaserDataResponse > getLaserDataResponsePtr;
typedef boost::shared_ptr< ::RoboCompLaserROS::getLaserDataResponse const> getLaserDataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator1> & lhs, const ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator1> & lhs, const ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace RoboCompLaserROS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6e451b02f31d668a623d66bbc12a30c";
  }

  static const char* value(const ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6e451b02f31d668ULL;
  static const uint64_t static_value2 = 0xa623d66bbc12a30cULL;
};

template<class ContainerAllocator>
struct DataType< ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RoboCompLaserROS/getLaserDataResponse";
  }

  static const char* value(const ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TLaserData response\n"
"\n"
"\n"
"================================================================================\n"
"MSG: RoboCompLaserROS/TLaserData\n"
"TData[] TLaserData\n"
"\n"
"================================================================================\n"
"MSG: RoboCompLaserROS/TData\n"
"float32 angle\n"
"float32 dist\n"
;
  }

  static const char* value(const ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getLaserDataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RoboCompLaserROS::getLaserDataResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    s << std::endl;
    Printer< ::RoboCompLaserROS::TLaserData_<ContainerAllocator> >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCOMPLASERROS_MESSAGE_GETLASERDATARESPONSE_H
