// Generated by gencpp from file RoboCompLaserROS/getLaserData.msg
// DO NOT EDIT!


#ifndef ROBOCOMPLASERROS_MESSAGE_GETLASERDATA_H
#define ROBOCOMPLASERROS_MESSAGE_GETLASERDATA_H

#include <ros/service_traits.h>


#include <RoboCompLaserROS/getLaserDataRequest.h>
#include <RoboCompLaserROS/getLaserDataResponse.h>


namespace RoboCompLaserROS
{

struct getLaserData
{

typedef getLaserDataRequest Request;
typedef getLaserDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getLaserData
} // namespace RoboCompLaserROS


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::RoboCompLaserROS::getLaserData > {
  static const char* value()
  {
    return "d6e451b02f31d668a623d66bbc12a30c";
  }

  static const char* value(const ::RoboCompLaserROS::getLaserData&) { return value(); }
};

template<>
struct DataType< ::RoboCompLaserROS::getLaserData > {
  static const char* value()
  {
    return "RoboCompLaserROS/getLaserData";
  }

  static const char* value(const ::RoboCompLaserROS::getLaserData&) { return value(); }
};


// service_traits::MD5Sum< ::RoboCompLaserROS::getLaserDataRequest> should match
// service_traits::MD5Sum< ::RoboCompLaserROS::getLaserData >
template<>
struct MD5Sum< ::RoboCompLaserROS::getLaserDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::RoboCompLaserROS::getLaserData >::value();
  }
  static const char* value(const ::RoboCompLaserROS::getLaserDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::RoboCompLaserROS::getLaserDataRequest> should match
// service_traits::DataType< ::RoboCompLaserROS::getLaserData >
template<>
struct DataType< ::RoboCompLaserROS::getLaserDataRequest>
{
  static const char* value()
  {
    return DataType< ::RoboCompLaserROS::getLaserData >::value();
  }
  static const char* value(const ::RoboCompLaserROS::getLaserDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::RoboCompLaserROS::getLaserDataResponse> should match
// service_traits::MD5Sum< ::RoboCompLaserROS::getLaserData >
template<>
struct MD5Sum< ::RoboCompLaserROS::getLaserDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::RoboCompLaserROS::getLaserData >::value();
  }
  static const char* value(const ::RoboCompLaserROS::getLaserDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::RoboCompLaserROS::getLaserDataResponse> should match
// service_traits::DataType< ::RoboCompLaserROS::getLaserData >
template<>
struct DataType< ::RoboCompLaserROS::getLaserDataResponse>
{
  static const char* value()
  {
    return DataType< ::RoboCompLaserROS::getLaserData >::value();
  }
  static const char* value(const ::RoboCompLaserROS::getLaserDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOCOMPLASERROS_MESSAGE_GETLASERDATA_H
