// Generated by gencpp from file RoboCompLaserROS/shortVector.msg
// DO NOT EDIT!


#ifndef ROBOCOMPLASERROS_MESSAGE_SHORTVECTOR_H
#define ROBOCOMPLASERROS_MESSAGE_SHORTVECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace RoboCompLaserROS
{
template <class ContainerAllocator>
struct shortVector_
{
  typedef shortVector_<ContainerAllocator> Type;

  shortVector_()
    : shortVector()  {
    }
  shortVector_(const ContainerAllocator& _alloc)
    : shortVector(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _shortVector_type;
  _shortVector_type shortVector;





  typedef boost::shared_ptr< ::RoboCompLaserROS::shortVector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RoboCompLaserROS::shortVector_<ContainerAllocator> const> ConstPtr;

}; // struct shortVector_

typedef ::RoboCompLaserROS::shortVector_<std::allocator<void> > shortVector;

typedef boost::shared_ptr< ::RoboCompLaserROS::shortVector > shortVectorPtr;
typedef boost::shared_ptr< ::RoboCompLaserROS::shortVector const> shortVectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RoboCompLaserROS::shortVector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RoboCompLaserROS::shortVector_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::RoboCompLaserROS::shortVector_<ContainerAllocator1> & lhs, const ::RoboCompLaserROS::shortVector_<ContainerAllocator2> & rhs)
{
  return lhs.shortVector == rhs.shortVector;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::RoboCompLaserROS::shortVector_<ContainerAllocator1> & lhs, const ::RoboCompLaserROS::shortVector_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace RoboCompLaserROS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompLaserROS::shortVector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompLaserROS::shortVector_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompLaserROS::shortVector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompLaserROS::shortVector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompLaserROS::shortVector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompLaserROS::shortVector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RoboCompLaserROS::shortVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "978066788cca8d820413339531a207a2";
  }

  static const char* value(const ::RoboCompLaserROS::shortVector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x978066788cca8d82ULL;
  static const uint64_t static_value2 = 0x0413339531a207a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::RoboCompLaserROS::shortVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RoboCompLaserROS/shortVector";
  }

  static const char* value(const ::RoboCompLaserROS::shortVector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RoboCompLaserROS::shortVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] shortVector\n"
;
  }

  static const char* value(const ::RoboCompLaserROS::shortVector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RoboCompLaserROS::shortVector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shortVector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct shortVector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RoboCompLaserROS::shortVector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RoboCompLaserROS::shortVector_<ContainerAllocator>& v)
  {
    s << indent << "shortVector[]" << std::endl;
    for (size_t i = 0; i < v.shortVector.size(); ++i)
    {
      s << indent << "  shortVector[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.shortVector[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCOMPLASERROS_MESSAGE_SHORTVECTOR_H
