// Generated by gencpp from file RoboCompLaserROS/TData.msg
// DO NOT EDIT!


#ifndef ROBOCOMPLASERROS_MESSAGE_TDATA_H
#define ROBOCOMPLASERROS_MESSAGE_TDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace RoboCompLaserROS
{
template <class ContainerAllocator>
struct TData_
{
  typedef TData_<ContainerAllocator> Type;

  TData_()
    : angle(0.0)
    , dist(0.0)  {
    }
  TData_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , dist(0.0)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;

   typedef float _dist_type;
  _dist_type dist;





  typedef boost::shared_ptr< ::RoboCompLaserROS::TData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RoboCompLaserROS::TData_<ContainerAllocator> const> ConstPtr;

}; // struct TData_

typedef ::RoboCompLaserROS::TData_<std::allocator<void> > TData;

typedef boost::shared_ptr< ::RoboCompLaserROS::TData > TDataPtr;
typedef boost::shared_ptr< ::RoboCompLaserROS::TData const> TDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RoboCompLaserROS::TData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RoboCompLaserROS::TData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::RoboCompLaserROS::TData_<ContainerAllocator1> & lhs, const ::RoboCompLaserROS::TData_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle &&
    lhs.dist == rhs.dist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::RoboCompLaserROS::TData_<ContainerAllocator1> & lhs, const ::RoboCompLaserROS::TData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace RoboCompLaserROS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompLaserROS::TData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompLaserROS::TData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompLaserROS::TData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompLaserROS::TData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompLaserROS::TData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompLaserROS::TData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RoboCompLaserROS::TData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e81e6f1a0c275da1e0b47fa67ac98907";
  }

  static const char* value(const ::RoboCompLaserROS::TData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe81e6f1a0c275da1ULL;
  static const uint64_t static_value2 = 0xe0b47fa67ac98907ULL;
};

template<class ContainerAllocator>
struct DataType< ::RoboCompLaserROS::TData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RoboCompLaserROS/TData";
  }

  static const char* value(const ::RoboCompLaserROS::TData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RoboCompLaserROS::TData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle\n"
"float32 dist\n"
;
  }

  static const char* value(const ::RoboCompLaserROS::TData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RoboCompLaserROS::TData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.dist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RoboCompLaserROS::TData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RoboCompLaserROS::TData_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "dist: ";
    Printer<float>::stream(s, indent + "  ", v.dist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCOMPLASERROS_MESSAGE_TDATA_H
