// Generated by gencpp from file RoboCompLaserROS/TLaserData.msg
// DO NOT EDIT!


#ifndef ROBOCOMPLASERROS_MESSAGE_TLASERDATA_H
#define ROBOCOMPLASERROS_MESSAGE_TLASERDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <RoboCompLaserROS/TData.h>

namespace RoboCompLaserROS
{
template <class ContainerAllocator>
struct TLaserData_
{
  typedef TLaserData_<ContainerAllocator> Type;

  TLaserData_()
    : TLaserData()  {
    }
  TLaserData_(const ContainerAllocator& _alloc)
    : TLaserData(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::RoboCompLaserROS::TData_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::RoboCompLaserROS::TData_<ContainerAllocator> >::other >  _TLaserData_type;
  _TLaserData_type TLaserData;





  typedef boost::shared_ptr< ::RoboCompLaserROS::TLaserData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RoboCompLaserROS::TLaserData_<ContainerAllocator> const> ConstPtr;

}; // struct TLaserData_

typedef ::RoboCompLaserROS::TLaserData_<std::allocator<void> > TLaserData;

typedef boost::shared_ptr< ::RoboCompLaserROS::TLaserData > TLaserDataPtr;
typedef boost::shared_ptr< ::RoboCompLaserROS::TLaserData const> TLaserDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RoboCompLaserROS::TLaserData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RoboCompLaserROS::TLaserData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::RoboCompLaserROS::TLaserData_<ContainerAllocator1> & lhs, const ::RoboCompLaserROS::TLaserData_<ContainerAllocator2> & rhs)
{
  return lhs.TLaserData == rhs.TLaserData;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::RoboCompLaserROS::TLaserData_<ContainerAllocator1> & lhs, const ::RoboCompLaserROS::TLaserData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace RoboCompLaserROS

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompLaserROS::TLaserData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompLaserROS::TLaserData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompLaserROS::TLaserData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompLaserROS::TLaserData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompLaserROS::TLaserData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompLaserROS::TLaserData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RoboCompLaserROS::TLaserData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7480408e277f96dda1ab467f0b2fd03";
  }

  static const char* value(const ::RoboCompLaserROS::TLaserData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7480408e277f96dULL;
  static const uint64_t static_value2 = 0xda1ab467f0b2fd03ULL;
};

template<class ContainerAllocator>
struct DataType< ::RoboCompLaserROS::TLaserData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RoboCompLaserROS/TLaserData";
  }

  static const char* value(const ::RoboCompLaserROS::TLaserData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RoboCompLaserROS::TLaserData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TData[] TLaserData\n"
"\n"
"================================================================================\n"
"MSG: RoboCompLaserROS/TData\n"
"float32 angle\n"
"float32 dist\n"
;
  }

  static const char* value(const ::RoboCompLaserROS::TLaserData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RoboCompLaserROS::TLaserData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.TLaserData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TLaserData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RoboCompLaserROS::TLaserData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RoboCompLaserROS::TLaserData_<ContainerAllocator>& v)
  {
    s << indent << "TLaserData[]" << std::endl;
    for (size_t i = 0; i < v.TLaserData.size(); ++i)
    {
      s << indent << "  TLaserData[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::RoboCompLaserROS::TData_<ContainerAllocator> >::stream(s, indent + "    ", v.TLaserData[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCOMPLASERROS_MESSAGE_TLASERDATA_H
